### PR TITLE
Improve ctx with fixed alpha channel

### PR DESCRIPTION
**Pull request by npentrel**
I fixed the rgba method to have values from 0-1.0 for alpha channel (as I think is customary) in the ctx library and added the error handling that there was a todo for.

### CODE REVIEW

**Comment by MatthewWilkes** [comment]
This looks good, but I'm not convinced that the comment here is correct, trying on an actual badge I'm having trouble getting correct behaviour for the 0..256 range for r,g,b

**Comment by npentrel** [comment]
Sorry which comment do you mean?

**Comment by npentrel** [comment]
I have only tested with the simulator where this does seem to work for me. What behaviour are you seeing?

**Comment by MatthewWilkes** [comment]
I meant the todo in the simulator code. It talks about automatically dispatching depending on the 0..255 or 0..1 ranges, if I'm understanding correctly. However, on the physical badge I was seeing only the 0..1 range working right. Let me check this again.

**Comment by npentrel** [comment]
Is that in `_sim.py`? I only see a TODO there about LEDs which is unrelated I think

**Comment by MatthewWilkes** [comment]
I'd meant the todo you referenced, but I double checked and it's working fine. I'm not sure what had confused me before, sorry for the delay merging.

**Pull request merged**
